### ISSUE TITLE
Update README to include note for python, gcc, make, and g++

### ISSUE THREAD

**Issue by bigicoin** [weijiekoh/caishen#1]
I wanted to try out the smart contract solidity tests, and I am starting on a pretty fresh machine that doesn't have much installed yet.

After cloning repo, I tried to do an npm install, and ran into error with `scrypt` expecting to have python. So I installed python, and ran into `scrypt` expecting to have a C compiler this time. I installed gcc and tried again and it expected to have make. I installed make and tried again and it wanted to have g++.

You may want to add a note about installing `python`, `gcc`, `make` and `g++` with `apt-get`/`yum`/`brew`.

**Comment by weijiekoh** [comment]
Thanks for the suggestion! I've updated the README accordingly.
